# Generated by Django 5.1.2 on 2025-02-24 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_department_dept_id_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department'),
        ),
    ]
