# Generated by Django 5.1.2 on 2025-03-15 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='reporting_manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_employees', to='app.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_employees', to='app.role'),
        ),
    ]
