# Generated by Django 5.1.2 on 2025-03-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_employee_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
